# -*- coding: utf-8 -*-
"""Pregunta2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NHgytXviJte1YcsLYtcnGa-Qr0nomCIQ
"""

import networkx as nx

def AL(G):
    gx = nx.Graph()
    nv = len(G)
    gx.add_nodes_from([u for u in range(nv)])
    for u in range(nv):
        for v in G[u]:
            gx.add_edge(u, v)
    nx.draw(gx, with_labels=True, node_color='orange', alpha = 0.75, node_size = 1000, node_shape ='p')


G = [[1, 2],
     [3, 4],
     [0, 4, 5],
     [1, 4],
     [ ],
     [0,2]]

def getmax(G):
    max = 0
    for i in range(6):
        var = len(G[i])
        if max < var:
            max = var
    print(max)    

AL(G)
getmax(G)